package wildbingo.wildbingo;

import org.bukkit.Bukkit;
import org.bukkit.ChatColor;

import java.io.*;
import java.util.ArrayList;
import java.util.List;

public class FileManager {
    private static String defaultMaterial = "ACACIA_BOAT\r\nACACIA_BUTTON\r\nACACIA_DOOR\r\nACACIA_FENCE\r\nACACIA_FENCE_GATE\r\nACACIA_LEAVES\r\nACACIA_LOG\r\nACACIA_PLANKS\r\nACACIA_PRESSURE_PLATE\r\nACACIA_SAPLING\r\nACACIA_SIGN\r\nACACIA_SLAB\r\nACACIA_STAIRS\r\nACACIA_TRAPDOOR\r\nACACIA_WOOD\r\nACTIVATOR_RAIL\r\nALLIUM\r\nANDESITE\r\nANDESITE_SLAB\r\nANDESITE_STAIRS\r\nANVIL\r\nAPPLE\r\nARMOR_STAND\r\nARROW\r\nAZURE_BLUET\r\nBAKED_POTATO\r\nBAMBOO\r\nBARREL\r\nBASALT\r\nBEEF\r\nBEETROOT\r\nBEETROOT_SEEDS\r\nBEETROOT_SOUP\r\nBELL\r\nBIRCH_BOAT\r\nBIRCH_BUTTON\r\nBIRCH_DOOR\r\nBIRCH_FENCE\r\nBIRCH_FENCE_GATE\r\nBIRCH_LEAVES\r\nBIRCH_LOG\r\nBIRCH_PLANKS\r\nBIRCH_PRESSURE_PLATE\r\nBIRCH_SAPLING\r\nBIRCH_SIGN\r\nBIRCH_SLAB\r\nBIRCH_STAIRS\r\nBIRCH_TRAPDOOR\r\nBIRCH_WOOD\r\nBLACKSTONE\r\nBLACKSTONE_SLAB\r\nBLACKSTONE_STAIRS\r\nBLACK_BANNER\r\nBLACK_BED\r\nBLACK_CARPET\r\nBLACK_CONCRETE\r\nBLACK_CONCRETE_POWDER\r\nBLACK_DYE\r\nBLACK_GLAZED_TERRACOTTA\r\nBLACK_STAINED_GLASS\r\nBLACK_STAINED_GLASS_PANE\r\nBLACK_TERRACOTTA\r\nBLACK_WOOL\r\nBLAST_FURNACE\r\nBLAZE_POWDER\r\nBLAZE_ROD\r\nBLUE_BANNER\r\nBLUE_BED\r\nBLUE_CARPET\r\nBLUE_CONCRETE\r\nBLUE_CONCRETE_POWDER\r\nBLUE_DYE\r\nBLUE_GLAZED_TERRACOTTA\r\nBLUE_ORCHID\r\nBLUE_STAINED_GLASS\r\nBLUE_STAINED_GLASS_PANE\r\nBLUE_TERRACOTTA\r\nBLUE_WOOL\r\nBONE\r\nBONE_BLOCK\r\nBONE_MEAL\r\nBOOKSHELF\r\nBOW\r\nBOWL\r\nBREAD\r\nBREWING_STAND\r\nBRICK\r\nBRICKS\r\nBRICK_SLAB\r\nBRICK_STAIRS\r\nBROWN_BANNER\r\nBROWN_BED\r\nBROWN_CARPET\r\nBROWN_CONCRETE\r\nBROWN_CONCRETE_POWDER\r\nBROWN_DYE\r\nBROWN_GLAZED_TERRACOTTA\r\nBROWN_MUSHROOM\r\nBROWN_STAINED_GLASS\r\nBROWN_STAINED_GLASS_PANE\r\nBROWN_TERRACOTTA\r\nBROWN_WOOL\r\nBUCKET\r\nCACTUS\r\nCAKE\r\nCAMPFIRE\r\nCARROT\r\nCARROT_ON_A_STICK\r\nCARTOGRAPHY_TABLE\r\nCARVED_PUMPKIN\r\nCAULDRON\r\nCHAIN\r\nCHARCOAL\r\nCHEST\r\nCHEST_MINECART\r\nCHICKEN\r\nCHIPPED_ANVIL\r\nCHISELED_NETHER_BRICKS\r\nCHISELED_POLISHED_BLACKSTONE\r\nCHISELED_QUARTZ_BLOCK\r\nCHISELED_RED_SANDSTONE\r\nCHISELED_SANDSTONE\r\nCHISELED_STONE_BRICKS\r\nCLAY\r\nCLAY_BALL\r\nCLOCK\r\nCOAL\r\nCOAL_BLOCK\r\nCOARSE_DIRT\r\nCOBBLESTONE\r\nCOBBLESTONE_SLAB\r\nCOBBLESTONE_STAIRS\r\nCOCOA_BEANS\r\nCOD\r\nCOD_BUCKET\r\nCOMPARATOR\r\nCOMPASS\r\nCOMPOSTER\r\nCOOKED_BEEF\r\nCOOKED_CHICKEN\r\nCOOKED_COD\r\nCOOKED_MUTTON\r\nCOOKED_PORKCHOP\r\nCOOKED_RABBIT\r\nCOOKED_SALMON\r\nCOOKIE\r\nCORNFLOWER\r\nCRACKED_NETHER_BRICKS\r\nCRACKED_POLISHED_BLACKSTONE_BRICKS\r\nCRACKED_STONE_BRICKS\r\nCRAFTING_TABLE\r\nCRIMSON_BUTTON\r\nCRIMSON_DOOR\r\nCRIMSON_FENCE\r\nCRIMSON_FENCE_GATE\r\nCRIMSON_FUNGUS\r\nCRIMSON_HYPHAE\r\nCRIMSON_PLANKS\r\nCRIMSON_PRESSURE_PLATE\r\nCRIMSON_ROOTS\r\nCRIMSON_SIGN\r\nCRIMSON_SLAB\r\nCRIMSON_STAIRS\r\nCRIMSON_STEM\r\nCRIMSON_TRAPDOOR\r\nCROSSBOW\r\nCRYING_OBSIDIAN\r\nCUT_RED_SANDSTONE\r\nCUT_RED_SANDSTONE_SLAB\r\nCUT_SANDSTONE\r\nCUT_SANDSTONE_SLAB\r\nCYAN_BANNER\r\nCYAN_BED\r\nCYAN_CARPET\r\nCYAN_CONCRETE\r\nCYAN_CONCRETE_POWDER\r\nCYAN_DYE\r\nCYAN_GLAZED_TERRACOTTA\r\nCYAN_STAINED_GLASS\r\nCYAN_STAINED_GLASS_PANE\r\nCYAN_TERRACOTTA\r\nCYAN_WOOL\r\nDAMAGED_ANVIL\r\nDANDELION\r\nDARK_OAK_BOAT\r\nDARK_OAK_BUTTON\r\nDARK_OAK_DOOR\r\nDARK_OAK_FENCE\r\nDARK_OAK_FENCE_GATE\r\nDARK_OAK_LEAVES\r\nDARK_OAK_LOG\r\nDARK_OAK_PLANKS\r\nDARK_OAK_PRESSURE_PLATE\r\nDARK_OAK_SAPLING\r\nDARK_OAK_SIGN\r\nDARK_OAK_SLAB\r\nDARK_OAK_STAIRS\r\nDARK_OAK_TRAPDOOR\r\nDARK_OAK_WOOD\r\nDAYLIGHT_DETECTOR\r\nDEAD_BUSH\r\nDETECTOR_RAIL\r\nDIAMOND\r\nDIAMOND_AXE\r\nDIAMOND_BLOCK\r\nDIAMOND_BOOTS\r\nDIAMOND_CHESTPLATE\r\nDIAMOND_HELMET\r\nDIAMOND_HOE\r\nDIAMOND_LEGGINGS\r\nDIAMOND_PICKAXE\r\nDIAMOND_SHOVEL\r\nDIAMOND_SWORD\r\nDIORITE\r\nDIORITE_SLAB\r\nDIORITE_STAIRS\r\nDIRT\r\nDISPENSER\r\nDRIED_KELP\r\nDRIED_KELP_BLOCK\r\nDROPPER\r\nEGG\r\nEMERALD\r\nEMERALD_BLOCK\r\nENCHANTING_TABLE\r\nENDER_CHEST\r\nENDER_EYE\r\nENDER_PEARL\r\nFEATHER\r\nFERMENTED_SPIDER_EYE\r\nFERN\r\nFIREWORK_ROCKET\r\nFIREWORK_STAR\r\nFIRE_CHARGE\r\nFISHING_ROD\r\nFLETCHING_TABLE\r\nFLINT\r\nFLINT_AND_STEEL\r\nFLOWER_POT\r\nFURNACE\r\nFURNACE_MINECART\r\nGHAST_TEAR\r\nGLASS\r\nGLASS_BOTTLE\r\nGLASS_PANE\r\nGLISTERING_MELON_SLICE\r\nGLOWSTONE\r\nGLOWSTONE_DUST\r\nGOLDEN_APPLE\r\nGOLDEN_AXE\r\nGOLDEN_BOOTS\r\nGOLDEN_CARROT\r\nGOLDEN_CHESTPLATE\r\nGOLDEN_HELMET\r\nGOLDEN_HOE\r\nGOLDEN_LEGGINGS\r\nGOLDEN_PICKAXE\r\nGOLDEN_SHOVEL\r\nGOLDEN_SWORD\r\nGOLD_BLOCK\r\nGOLD_INGOT\r\nGOLD_NUGGET\r\nGRANITE\r\nGRANITE_SLAB\r\nGRANITE_STAIRS\r\nGRASS\r\nGRAVEL\r\nGRAY_BANNER\r\nGRAY_BED\r\nGRAY_CARPET\r\nGRAY_CONCRETE\r\nGRAY_CONCRETE_POWDER\r\nGRAY_DYE\r\nGRAY_GLAZED_TERRACOTTA\r\nGRAY_STAINED_GLASS\r\nGRAY_STAINED_GLASS_PANE\r\nGRAY_TERRACOTTA\r\nGRAY_WOOL\r\nGREEN_BANNER\r\nGREEN_BED\r\nGREEN_CARPET\r\nGREEN_CONCRETE\r\nGREEN_CONCRETE_POWDER\r\nGREEN_DYE\r\nGREEN_GLAZED_TERRACOTTA\r\nGREEN_STAINED_GLASS\r\nGREEN_STAINED_GLASS_PANE\r\nGREEN_TERRACOTTA\r\nGREEN_WOOL\r\nGRINDSTONE\r\nGUNPOWDER\r\nHAY_BLOCK\r\nHEART_OF_THE_SEA\r\nHEAVY_WEIGHTED_PRESSURE_PLATE\r\nHOPPER\r\nHOPPER_MINECART\r\nINK_SAC\r\nIRON_AXE\r\nIRON_BARS\r\nIRON_BLOCK\r\nIRON_BOOTS\r\nIRON_CHESTPLATE\r\nIRON_DOOR\r\nIRON_HELMET\r\nIRON_HOE\r\nIRON_INGOT\r\nIRON_LEGGINGS\r\nIRON_NUGGET\r\nIRON_PICKAXE\r\nIRON_SHOVEL\r\nIRON_SWORD\r\nIRON_TRAPDOOR\r\nITEM_FRAME\r\nJACK_O_LANTERN\r\nJUKEBOX\r\nJUNGLE_BOAT\r\nJUNGLE_BUTTON\r\nJUNGLE_DOOR\r\nJUNGLE_FENCE\r\nJUNGLE_FENCE_GATE\r\nJUNGLE_LEAVES\r\nJUNGLE_LOG\r\nJUNGLE_PLANKS\r\nJUNGLE_PRESSURE_PLATE\r\nJUNGLE_SAPLING\r\nJUNGLE_SIGN\r\nJUNGLE_SLAB\r\nJUNGLE_STAIRS\r\nJUNGLE_TRAPDOOR\r\nJUNGLE_WOOD\r\nKELP\r\nLADDER\r\nLANTERN\r\nLAPIS_BLOCK\r\nLAPIS_LAZULI\r\nLAVA_BUCKET\r\nLEAD\r\nLEATHER\r\nLEATHER_BOOTS\r\nLEATHER_CHESTPLATE\r\nLEATHER_HELMET\r\nLEATHER_HORSE_ARMOR\r\nLEATHER_LEGGINGS\r\nLECTERN\r\nLEVER\r\nLIGHT_BLUE_BANNER\r\nLIGHT_BLUE_BED\r\nLIGHT_BLUE_CARPET\r\nLIGHT_BLUE_CONCRETE\r\nLIGHT_BLUE_CONCRETE_POWDER\r\nLIGHT_BLUE_DYE\r\nLIGHT_BLUE_GLAZED_TERRACOTTA\r\nLIGHT_BLUE_STAINED_GLASS\r\nLIGHT_BLUE_STAINED_GLASS_PANE\r\nLIGHT_BLUE_TERRACOTTA\r\nLIGHT_BLUE_WOOL\r\nLIGHT_GRAY_BANNER\r\nLIGHT_GRAY_BED\r\nLIGHT_GRAY_CARPET\r\nLIGHT_GRAY_CONCRETE\r\nLIGHT_GRAY_CONCRETE_POWDER\r\nLIGHT_GRAY_DYE\r\nLIGHT_GRAY_GLAZED_TERRACOTTA\r\nLIGHT_GRAY_STAINED_GLASS\r\nLIGHT_GRAY_STAINED_GLASS_PANE\r\nLIGHT_GRAY_TERRACOTTA\r\nLIGHT_GRAY_WOOL\r\nLIGHT_WEIGHTED_PRESSURE_PLATE\r\nLILAC\r\nLILY_OF_THE_VALLEY\r\nLILY_PAD\r\nLIME_BANNER\r\nLIME_BED\r\nLIME_CARPET\r\nLIME_CONCRETE\r\nLIME_CONCRETE_POWDER\r\nLIME_DYE\r\nLIME_GLAZED_TERRACOTTA\r\nLIME_STAINED_GLASS\r\nLIME_STAINED_GLASS_PANE\r\nLIME_TERRACOTTA\r\nLIME_WOOL\r\nLOOM\r\nMAGENTA_BANNER\r\nMAGENTA_BED\r\nMAGENTA_CARPET\r\nMAGENTA_CONCRETE\r\nMAGENTA_CONCRETE_POWDER\r\nMAGENTA_DYE\r\nMAGENTA_GLAZED_TERRACOTTA\r\nMAGENTA_STAINED_GLASS\r\nMAGENTA_STAINED_GLASS_PANE\r\nMAGENTA_TERRACOTTA\r\nMAGENTA_WOOL\r\nMAGMA_BLOCK\r\nMAGMA_CREAM\r\nMAP\r\nMELON\r\nMELON_SEEDS\r\nMELON_SLICE\r\nMILK_BUCKET\r\nMINECART\r\nMOSSY_COBBLESTONE\r\nMOSSY_COBBLESTONE_SLAB\r\nMOSSY_COBBLESTONE_STAIRS\r\nMOSSY_STONE_BRICKS\r\nMOSSY_STONE_BRICK_SLAB\r\nMOSSY_STONE_BRICK_STAIRS\r\nMUSHROOM_STEW\r\nMUTTON\r\nNETHERRACK\r\nNETHER_BRICK\r\nNETHER_BRICKS\r\nNETHER_BRICK_FENCE\r\nNETHER_BRICK_SLAB\r\nNETHER_BRICK_STAIRS\r\nNETHER_SPROUTS\r\nNETHER_WART\r\nNETHER_WART_BLOCK\r\nNOTE_BLOCK\r\nOAK_BOAT\r\nOAK_BUTTON\r\nOAK_DOOR\r\nOAK_FENCE\r\nOAK_FENCE_GATE\r\nOAK_LEAVES\r\nOAK_LOG\r\nOAK_PLANKS\r\nOAK_PRESSURE_PLATE\r\nOAK_SAPLING\r\nOAK_SIGN\r\nOAK_SLAB\r\nOAK_STAIRS\r\nOAK_TRAPDOOR\r\nOAK_WOOD\r\nOBSERVER\r\nOBSIDIAN\r\nORANGE_BANNER\r\nORANGE_BED\r\nORANGE_CARPET\r\nORANGE_CONCRETE\r\nORANGE_CONCRETE_POWDER\r\nORANGE_DYE\r\nORANGE_GLAZED_TERRACOTTA\r\nORANGE_STAINED_GLASS\r\nORANGE_STAINED_GLASS_PANE\r\nORANGE_TERRACOTTA\r\nORANGE_TULIP\r\nORANGE_WOOL\r\nOXEYE_DAISY\r\nPAINTING\r\nPAPER\r\nPEONY\r\nPETRIFIED_OAK_SLAB\r\nPINK_BANNER\r\nPINK_BED\r\nPINK_CARPET\r\nPINK_CONCRETE\r\nPINK_CONCRETE_POWDER\r\nPINK_DYE\r\nPINK_GLAZED_TERRACOTTA\r\nPINK_STAINED_GLASS\r\nPINK_STAINED_GLASS_PANE\r\nPINK_TERRACOTTA\r\nPINK_TULIP\r\nPINK_WOOL\r\nPISTON\r\nPOISONOUS_POTATO\r\nPOLISHED_ANDESITE\r\nPOLISHED_ANDESITE_SLAB\r\nPOLISHED_ANDESITE_STAIRS\r\nPOLISHED_BASALT\r\nPOLISHED_BLACKSTONE\r\nPOLISHED_BLACKSTONE_BRICKS\r\nPOLISHED_BLACKSTONE_BRICK_SLAB\r\nPOLISHED_BLACKSTONE_BRICK_STAIRS\r\nPOLISHED_BLACKSTONE_BUTTON\r\nPOLISHED_BLACKSTONE_PRESSURE_PLATE\r\nPOLISHED_BLACKSTONE_SLAB\r\nPOLISHED_BLACKSTONE_STAIRS\r\nPOLISHED_DIORITE\r\nPOLISHED_DIORITE_SLAB\r\nPOLISHED_DIORITE_STAIRS\r\nPOLISHED_GRANITE\r\nPOLISHED_GRANITE_SLAB\r\nPOLISHED_GRANITE_STAIRS\r\nPOPPY\r\nPORKCHOP\r\nPOTATO\r\nPOWERED_RAIL\r\nPUFFERFISH\r\nPUFFERFISH_BUCKET\r\nPUMPKIN\r\nPUMPKIN_PIE\r\nPUMPKIN_SEEDS\r\nPURPLE_BANNER\r\nPURPLE_BED\r\nPURPLE_CARPET\r\nPURPLE_CONCRETE\r\nPURPLE_CONCRETE_POWDER\r\nPURPLE_DYE\r\nPURPLE_GLAZED_TERRACOTTA\r\nPURPLE_STAINED_GLASS\r\nPURPLE_STAINED_GLASS_PANE\r\nPURPLE_TERRACOTTA\r\nPURPLE_WOOL\r\nQUARTZ\r\nQUARTZ_BLOCK\r\nQUARTZ_BRICKS\r\nQUARTZ_PILLAR\r\nQUARTZ_SLAB\r\nQUARTZ_STAIRS\r\nRABBIT\r\nRABBIT_FOOT\r\nRABBIT_HIDE\r\nRABBIT_STEW\r\nRAIL\r\nREDSTONE\r\nREDSTONE_BLOCK\r\nREDSTONE_LAMP\r\nREDSTONE_TORCH\r\nRED_BANNER\r\nRED_BED\r\nRED_CARPET\r\nRED_CONCRETE\r\nRED_CONCRETE_POWDER\r\nRED_DYE\r\nRED_GLAZED_TERRACOTTA\r\nRED_MUSHROOM\r\nRED_NETHER_BRICKS\r\nRED_NETHER_BRICK_SLAB\r\nRED_NETHER_BRICK_STAIRS\r\nRED_SAND\r\nRED_SANDSTONE\r\nRED_SANDSTONE_SLAB\r\nRED_SANDSTONE_STAIRS\r\nRED_STAINED_GLASS\r\nRED_STAINED_GLASS_PANE\r\nRED_TERRACOTTA\r\nRED_TULIP\r\nRED_WOOL\r\nREPEATER\r\nRESPAWN_ANCHOR\r\nROSE_BUSH\r\nROTTEN_FLESH\r\nSADDLE\r\nSALMON\r\nSALMON_BUCKET\r\nSAND\r\nSANDSTONE\r\nSANDSTONE_SLAB\r\nSANDSTONE_STAIRS\r\nSCAFFOLDING\r\nSHEARS\r\nSHIELD\r\nSHROOMLIGHT\r\nSLIME_BALL\r\nSLIME_BLOCK\r\nSMITHING_TABLE\r\nSMOKER\r\nSMOOTH_QUARTZ\r\nSMOOTH_QUARTZ_SLAB\r\nSMOOTH_QUARTZ_STAIRS\r\nSMOOTH_RED_SANDSTONE\r\nSMOOTH_RED_SANDSTONE_SLAB\r\nSMOOTH_RED_SANDSTONE_STAIRS\r\nSMOOTH_SANDSTONE\r\nSMOOTH_SANDSTONE_SLAB\r\nSMOOTH_SANDSTONE_STAIRS\r\nSMOOTH_STONE\r\nSMOOTH_STONE_SLAB\r\nSNOW\r\nSNOWBALL\r\nSNOW_BLOCK\r\nSOUL_CAMPFIRE\r\nSOUL_LANTERN\r\nSOUL_SAND\r\nSOUL_SOIL\r\nSOUL_TORCH\r\nSPECTRAL_ARROW\r\nSPIDER_EYE\r\nSPRUCE_BOAT\r\nSPRUCE_BUTTON\r\nSPRUCE_DOOR\r\nSPRUCE_FENCE\r\nSPRUCE_FENCE_GATE\r\nSPRUCE_LEAVES\r\nSPRUCE_LOG\r\nSPRUCE_PLANKS\r\nSPRUCE_PRESSURE_PLATE\r\nSPRUCE_SAPLING\r\nSPRUCE_SIGN\r\nSPRUCE_SLAB\r\nSPRUCE_STAIRS\r\nSPRUCE_TRAPDOOR\r\nSPRUCE_WOOD\r\nSTICK\r\nSTICKY_PISTON\r\nSTONE\r\nSTONECUTTER\r\nSTONE_AXE\r\nSTONE_BRICKS\r\nSTONE_BRICK_SLAB\r\nSTONE_BRICK_STAIRS\r\nSTONE_BUTTON\r\nSTONE_HOE\r\nSTONE_PICKAXE\r\nSTONE_PRESSURE_PLATE\r\nSTONE_SHOVEL\r\nSTONE_SLAB\r\nSTONE_STAIRS\r\nSTONE_SWORD\r\nSTRING\r\nSTRIPPED_ACACIA_LOG\r\nSTRIPPED_ACACIA_WOOD\r\nSTRIPPED_BIRCH_LOG\r\nSTRIPPED_BIRCH_WOOD\r\nSTRIPPED_CRIMSON_HYPHAE\r\nSTRIPPED_CRIMSON_STEM\r\nSTRIPPED_DARK_OAK_LOG\r\nSTRIPPED_DARK_OAK_WOOD\r\nSTRIPPED_JUNGLE_LOG\r\nSTRIPPED_JUNGLE_WOOD\r\nSTRIPPED_OAK_LOG\r\nSTRIPPED_OAK_WOOD\r\nSTRIPPED_SPRUCE_LOG\r\nSTRIPPED_SPRUCE_WOOD\r\nSTRIPPED_WARPED_HYPHAE\r\nSTRIPPED_WARPED_STEM\r\nSUGAR\r\nSUGAR_CANE\r\nSUNFLOWER\r\nSUSPICIOUS_STEW\r\nSWEET_BERRIES\r\nTARGET\r\nTERRACOTTA\r\nTNT\r\nTNT_MINECART\r\nTORCH\r\nTRAPPED_CHEST\r\nTRIPWIRE_HOOK\r\nTROPICAL_FISH\r\nTROPICAL_FISH_BUCKET\r\nTWISTING_VINES\r\nVINE\r\nWARPED_BUTTON\r\nWARPED_DOOR\r\nWARPED_FENCE\r\nWARPED_FENCE_GATE\r\nWARPED_FUNGUS\r\nWARPED_FUNGUS_ON_A_STICK\r\nWARPED_HYPHAE\r\nWARPED_PLANKS\r\nWARPED_PRESSURE_PLATE\r\nWARPED_ROOTS\r\nWARPED_SIGN\r\nWARPED_SLAB\r\nWARPED_STAIRS\r\nWARPED_STEM\r\nWARPED_TRAPDOOR\r\nWARPED_WART_BLOCK\r\nWATER_BUCKET\r\nWEEPING_VINES\r\nWHEAT_SEEDS\r\nWHITE_BANNER\r\nWHITE_BED\r\nWHITE_CARPET\r\nWHITE_CONCRETE\r\nWHITE_CONCRETE_POWDER\r\nWHITE_DYE\r\nWHITE_GLAZED_TERRACOTTA\r\nWHITE_STAINED_GLASS\r\nWHITE_STAINED_GLASS_PANE\r\nWHITE_TERRACOTTA\r\nWHITE_TULIP\r\nWHITE_WOOL\r\nWOODEN_AXE\r\nWOODEN_HOE\r\nWOODEN_PICKAXE\r\nWOODEN_SHOVEL\r\nWOODEN_SWORD\r\nWRITABLE_BOOK\r\nWRITTEN_BOOK\r\nYELLOW_BANNER\r\nYELLOW_BED\r\nYELLOW_CARPET\r\nYELLOW_CONCRETE\r\nYELLOW_CONCRETE_POWDER\r\nYELLOW_DYE\r\nYELLOW_GLAZED_TERRACOTTA\r\nYELLOW_STAINED_GLASS\r\nYELLOW_STAINED_GLASS_PANE\r\nYELLOW_TERRACOTTA\r\nYELLOW_WOOL\r\n";

    public static String[] getItemList(){
        File fileName = new File("plugins\\WildBingo\\" + "material.yml");
        try {
            BufferedReader fr = new BufferedReader(new FileReader(fileName));
            List list = new ArrayList();
            String s;
            while((s = fr.readLine()) != null){
                list.add(Cutter(s));
            }
            fr.close();
            String[] itemList = new String[list.toArray().length];
            for(int count = 0; count < list.toArray().length; count++){
                itemList[count] = list.get(count).toString();
            }
            return itemList;
        } catch (FileNotFoundException e) {
            System.out.println("ERROR : 리스트 불러오는중 오류 발생");
        } catch (IOException e) {
            System.out.println("ERROR : 리스트 불러오는중 오류 발생");
        }
        return null;
    }

    public static void setDefaultMaterial(){
        File fileName = new File("plugins\\WildBingo\\" + "material.yml");
        try{
            if(!fileName.exists()){
                fileName.createNewFile();
                FileWriter fw = new FileWriter(fileName, true);
                fw.write(defaultMaterial);
                fw.flush();
                fw.close();
                System.out.println("초기 아이템 설정값이 생성되었습니다.");
            }else{
                System.out.println("초기 설정값이 이미 존재합니다.");
            }

        } catch (IOException e) {
            Bukkit.broadcastMessage("파일 경로를 찾을 수 없습니다.");
            Bukkit.broadcastMessage("폴더를 생성합니다.");
//            e.printStackTrace();
            File loc_file = new File("plugins\\WildBingo");
            loc_file.mkdirs();

            try {
                FileWriter fw = new FileWriter(fileName, true);
                fw.write(defaultMaterial);
                fw.flush();
                fw.close();
                System.out.println("초기 아이템 설정값이 생성되었습니다.");
            }catch (IOException e2) {
                System.out.println("ERROR : 초기 설정값 생성중 오류 발생");
            }
        }
    }

    public static String Cutter(String line){
        String cut = line;
        return cut;
    }
}
